name: Build lsplant-standalone aar

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Set up Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
        with:
          version: 1.12.1

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Remove Android bundled CMake
        run: rm -rf "$ANDROID_HOME/cmake"

      - name: Grant execute permission
        run: chmod +x ./gradlew

      - name: Build standalone aar
        run: ./gradlew :lsplant:assembleStandalone --stacktrace

      - name: Upload aar
        uses: actions/upload-artifact@v4
        with:
          name: lsplant-standalone-aar
          path: lsplant/build/outputs/aar/*.aar
